// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eperxgscydavxauiryju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZXJ4Z3NjeWRhdnhhdWlyeWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDM0NjksImV4cCI6MjA2MTYxOTQ2OX0.F6RDaLEmHrYCm0TH6fBnTx_trbaInK1MfYaCVf62Vqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);